services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcreve-audio-api
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    volumes:
    
      - ./temp:/app/temp
    restart: unless-stopped