services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-transcriber-api
    ports:
      - "3000:3000"
    # Monta o arquivo .env de fora para dentro do container
    env_file:
      - .env
    volumes:
      # Volume para o diretório temporário, caso queira inspecionar
      - ./temp:/app/temp
    restart: unless-stopped